version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    expose:
      - "80"

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    container_name: admin
    expose:
      - "80"

  nginx:
    image: arm32v7/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - admin

  mongo:
    image: arm32v7/mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
  uploads:
